### ISSUE TITLE
Input format for create_ondisc_matrix_from_R_matrix()

### ISSUE THREAD

**Issue by ekatsevi** [timothy-barry/ondisc#18]
I tried passing a sparse matrix in `dgCMatrix` format to `create_ondisc_matrix_from_R_matrix()`, but it said that the input is required to be in `dgRMatrix` format (or perhaps it could also be in dense format). Could you please add support for `dgCMatrix` input?

**Comment by ekatsevi** [comment]
Here is the error message I got when trying to input a `dgCMatrix`:

![image](https://user-images.githubusercontent.com/13232324/159581568-7ce4f4c5-846a-4b1b-aa79-535f39ec484f.png)

**Comment by timothy-barry** [comment]
Thanks. Issue resolved with commit https://github.com/timothy-barry/ondisc/commit/191c324234be3fa1f5316cf26800d697970b7ba0.
